-- Переводы карточек курсов на языки витрин (казахский, узбекский).
-- Переносим текстами, а не машинным переводом на лету: карточка курса — это то,
-- что читает покупатель и индексирует поисковик. Материалы курса остаются
-- русскими, и на самой карточке это написано явно (t.course.courseLanguage).
-- Привязка по slug: id курса на dev и проде разные. Повторный запуск ничего
-- не задваивает и не затирает ручные правки — ON CONFLICT DO NOTHING.

INSERT INTO "CourseTranslation" ("id", "courseId", "locale", "title", "subtitle", "description", "updatedAt")
SELECT 'ctr_kk_sales-b2b', "id", 'kk', 'B2B келіссөздер және ірі мәмілелер', 'Қысым, сауда-саттық және ШҚҚТ-мен жұмыс: келіссөз — басқарылатын процесс', 'Бизнес-тренер Виталий Дубовиктің іскерлік келіссөздер мен B2B сатылымдар бойынша тірі тренингі және жүйелі курсы. Жеті модульде 28 сабақ: нарыққа реакция орнына белсенді дайындық, клиент компаниясындағы рөлдер картасы (ШҚҚТ, ШӘТТ, ШҚДТ) және шұңқыр математикасы, келіссөздің төрт түрі — «темір, қола, күміс, алтын» — 11 манипуляция тактикасын талдаумен, VIP-келіссөздер және СПИН әдістемесі. Одан әрі — B2B сатылымның 11 сабақтан тұратын жүйесі: лидтерді сегменттеу, клиенттің жолы және кезеңдер конверсиясы, ұстап қалу, күшті коммерциялық ұсыныс, келісімдерді бекіту. Содан соң баға мен премиум сегмент блогы — серіктес қажеттіліктерінің пирамидасы, күрделі әрі қымбат өнімді сату, суық қоңыраулар, қақтығыстар, GAPP-талдау. Финалда — далада жұмыс: сауда өкілінің қателері және желіге кіру. Соңында — сабақтар мазмұны бойынша 20 сұрақтан тұратын қорытынды тест.', NOW()
FROM "Course" WHERE "slug" = 'sales-b2b'
ON CONFLICT ("courseId", "locale") DO NOTHING;
INSERT INTO "CourseTranslation" ("id", "courseId", "locale", "title", "subtitle", "description", "updatedAt")
SELECT 'ctr_kk_sales-kitchens', "id", 'kk', 'Ас үй жиһазын тиімді сату 2.0', 'Ас үй дизайнерінің толық курсы: мессенджердегі лидтен қол қойылған шартқа дейін', 'Бизнес-тренер Виталий Дубовиктің (activesales.by) ас үй жиһазының дизайнерлері мен сатушыларына арналған үлкен бейнекурсы. 33 сабақ және алты сағатқа жуық практика: ас үй нарығы қалай құрылған және онда кім ойнайды, лидтердің қандай көздері жұмыс істейді, салонда нені істеуге болады және нені болмайды, мессенджерлерде хат алмасуды және дайын сценарий бойынша қоңырауларды қалай жүргізу керек, дизайнердің чек-парағы және шарт жасауға арналған 7 кеңес, сатып алушы психологиясы түрлері бойынша, 13 типтік қате және 10 алтын ереже, байланыс орнатудың 10 тәсілі, қажеттіліктермен жұмыс және ұсынысты бейімдеу, қарсылықтарды пысықтау, қақтығыстарды шешу, мәмілені аяқтау және сатудан кейінгі қызмет көрсету.', NOW()
FROM "Course" WHERE "slug" = 'sales-kitchens'
ON CONFLICT ("courseId", "locale") DO NOTHING;
INSERT INTO "CourseTranslation" ("id", "courseId", "locale", "title", "subtitle", "description", "updatedAt")
SELECT 'ctr_kk_sales-pharma', "id", 'kk', 'Медициналық өкілдерге арналған белсенді сату', 'Фармацевтика бизнесінде дәрігерлермен және дәріханалармен жұмыс техникалары', 'Медициналық өкілдерге, өңірлік менеджерлерге және фармацевтикалық компания қызметкерлеріне арналған бейнекурс. Қажеттілікті анықтау, бәсекелестермен жұмыс, сендіру және мәмілені жабу бойынша 15 практикалық сабақ. СПИН әдістемесі, қақтығыс жағдайларын талдау, медөкілдің 3 алтын ережесі. Барлық сабақты сату бойынша қолданыстағы бизнес-тренер жазған.', NOW()
FROM "Course" WHERE "slug" = 'sales-pharma'
ON CONFLICT ("courseId", "locale") DO NOTHING;
INSERT INTO "CourseTranslation" ("id", "courseId", "locale", "title", "subtitle", "description", "updatedAt")
SELECT 'ctr_kk_sales-realty', "id", 'kk', 'Жылжымайтын мүлікті сату техникалары', 'Риэлтордың алты қатесі және клиентті мәмілеге жеткізетін тактика', 'Бизнес-тренер Виталий Дубовиктің (activesales.by) риэлторларға, агенттерге және жылжымайтын мүлік агенттіктерінің басшыларына арналған практикалық бейнекурсы. Жеке тұлғаларға сату туралы 9 сабақ: пәтер сатудың басқа сатылымдардан айырмашылығы неде және риэлтор қызметінің құндылығы қандай, пәтер сатушысының басында шын мәнінде не болып жатыр (сегіз туыс, енесі және БАҚ-тан құралған айсберг), клиенттің өзі баға түсіру туралы айтатын үш қадам тактикасы, және алты типтік қатенің тұтас талдауы: жай жалқаулық пен жауап беру жылдамдығы, пәтерді нарықтан төмен «құтылту» әрекеті, отбасымен және эксклюзивпен манипуляция, үстірт анықталған қажеттіліктер, қарсылықпен жұмыс істей алмау және қақтығыста беделден айырылу.', NOW()
FROM "Course" WHERE "slug" = 'sales-realty'
ON CONFLICT ("courseId", "locale") DO NOTHING;
INSERT INTO "CourseTranslation" ("id", "courseId", "locale", "title", "subtitle", "description", "updatedAt")
SELECT 'ctr_kk_sales-shoes', "id", 'kk', 'Аяқ киім және киім дүкеніндегі сату', 'Сауда залындағы сатудың жеті кезеңі: байланыстан екінші жұпқа дейін', 'Бизнес-тренер Виталий Дубовиктен (activesales.by) аяқ киім және киім салондарының сатушы-кеңесшілеріне арналған практикалық бейнекурс. Бес сабақ — залдағы сатып алушымен жұмыстың бүкіл циклі: сауда залында қалай орналасу және жақындауға сәтті сәтті ұстау, қандай сұрақтармен қажеттілікті анықтау, пайда тілінде таныстыруды қалай жасау және үш қорапты дұрыс шығару, «қымбат», «мен жай қарап жүрмін», «беймәлім брендтен қорқамын» және «ойланып көрейін» дегенге қалай жауап беру, чекті екінші жұппен және аяқ киім күтімімен қалай кеңейту, сатуды аяқтаудың сегіз тәсілі және сатып алушыны сатып алмай кетуге мәжбүрлейтін аяқ киім сатушысының 13 типтік қатесі.', NOW()
FROM "Course" WHERE "slug" = 'sales-shoes'
ON CONFLICT ("courseId", "locale") DO NOTHING;
INSERT INTO "CourseTranslation" ("id", "courseId", "locale", "title", "subtitle", "description", "updatedAt")
SELECT 'ctr_kk_sales-spin', "id", 'kk', 'СПИН-сату: қажеттілікті қалай қалыптастыру керек', 'Клиентті сатып алу шешіміне жеткізетін сұрақтардың төрт түрі', 'Бизнес-тренер Виталий Дубовиктен (activesales.by) СПИН әдісі бойынша практикалық бейнекурс. Сатушылардың көбі қажеттілікті ашық сұрақтармен анықтай алады, бірақ оны қалыптастыруды бірде-бірі дерлік білмейді — ал дәл осы кеңесшіні сатушыдан ажыратады. Жеті сабақ: сұрақтардың төрт түрі (ситуациялық, проблемалық, шығарушы, бағыттаушы), «факт → пайда → келісім» таныстыру схемасы және алты салаға арналған дайын сұрақ жинақтары — құрылыс супермаркеті мен DIY, сағат салоны, B2B-ге жабдық жеткізу, банк және лизинг, сараптамалық қызметтерді сату және тіпті баламен оқу туралы әңгіме.', NOW()
FROM "Course" WHERE "slug" = 'sales-spin'
ON CONFLICT ("courseId", "locale") DO NOTHING;
INSERT INTO "CourseTranslation" ("id", "courseId", "locale", "title", "subtitle", "description", "updatedAt")
SELECT 'ctr_kk_sales-tourism', "id", 'kk', 'Туризмдегі сату техникалары', 'Кіріс қоңыраудан қайталанатын сапарға дейін: алгоритм, сұрақтар, турист түрлері', 'Бизнес-тренер Виталий Дубовиктің (activesales.by) турагенттіктер мен туроператорлардың менеджерлеріне арналған практикалық бейнекурсы. Нақты тренинг бойынша 13 сабақ: туристің шешімі неден құралады (өнім, компания және сатушы — сатушыға ықпалдың 87 %-ына дейіні тиесілі), сатушының төрт рөлі, мәміле циклі турист көзімен, типтік қателер мен қауіп аймақтары, тоғыз қадамнан тұратын кіріс қоңырау алгоритмі, сұрақтар шұңқыры (ашық → баламалы → жабық), туристтердің төрт түрі және әрқайсысына бейімделу, «қымбат», «мен жай зерттеп жүрмін» және «ойланып көрейін» дегенге дайын жауаптар, қақтығыспен жұмыс, мәмілені жабудың бес тәсілі және сапардан кейін туристі қайтару.', NOW()
FROM "Course" WHERE "slug" = 'sales-tourism'
ON CONFLICT ("courseId", "locale") DO NOTHING;
INSERT INTO "CourseTranslation" ("id", "courseId", "locale", "title", "subtitle", "description", "updatedAt")
SELECT 'ctr_kk_time-management', "id", 'kk', 'Тайм-менеджмент: негізгі принциптер', 'Басымдықтар, мақсаттар және уақытты басқару құралдары — Виталий Дубовиктің тренингі', 'Бизнес-тренер Виталий Дубовиктен (activesales.by) тайм-менеджмент бойынша практикалық бейнекурс. 18 сабақ — базалық принциптерден дайын құралдарға дейін: Эйзенхауэр матрицасы бойынша басымдықтарды қалай қою керек, күнді 60/40 ережесімен жоспарлау, «бақадан» бастау, ірі міндеттерді «піл» және «үш шеге» техникасымен бөлшектеу, мақсатты дұрыс қою, күнделік пен Google Күнтізбесін жүргізу, хронометраж арқылы «уақыт жегіштерін» табу және кеңседе де, қашықтан да өнімді жұмысты ұйымдастыру. Материал B2B-дегі тірі тренингтерде түсірілген, бірақ барлық модель әмбебап.', NOW()
FROM "Course" WHERE "slug" = 'time-management'
ON CONFLICT ("courseId", "locale") DO NOTHING;
INSERT INTO "CourseTranslation" ("id", "courseId", "locale", "title", "subtitle", "description", "updatedAt")
SELECT 'ctr_uz_sales-b2b', "id", 'uz', 'B2B muzokaralar va yirik bitimlar', 'Bosim, savdolashuv va QQSh bilan ishlash: muzokara — boshqariladigan jarayon', 'Biznes-trener Vitaliy Dubovikning ishbilarmonlik muzokaralari va B2B sotuv bo''yicha jonli treningi hamda tizimli kursi. Yetti modulda 28 dars: bozorga munosabat bildirish o''rniga proaktiv tayyorgarlik, mijoz kompaniyasidagi rollar xaritasi (QQSh, TBSh, QRSh) va voronka matematikasi, muzokaraning to''rt turi — «temir, bronza, kumush, oltin» — 11 ta manipulyatsiya taktikasi tahlili bilan, VIP-muzokaralar va SPIN metodikasi. Keyin — B2B sotuvning 11 darsdan iborat tizimi: lidlarni segmentlash, mijoz yo''li va bosqichlar konversiyasi, ushlab qolish, kuchli tijorat taklifi, kelishuvlarni qayd etish. So''ngra narx va premium segment bloki — hamkor ehtiyojlari piramidasi, murakkab va qimmat mahsulotni sotish, sovuq qo''ng''iroqlar, nizolar, GAPP-tahlil. Yakunida — maydondagi ish: savdo vakilining xatolari va tarmoqqa kirish. Oxirida — darslar mazmuni bo''yicha 20 savoldan iborat yakuniy test.', NOW()
FROM "Course" WHERE "slug" = 'sales-b2b'
ON CONFLICT ("courseId", "locale") DO NOTHING;
INSERT INTO "CourseTranslation" ("id", "courseId", "locale", "title", "subtitle", "description", "updatedAt")
SELECT 'ctr_uz_sales-kitchens', "id", 'uz', 'Oshxona mebelini samarali sotish 2.0', 'Oshxona dizayneri uchun to''liq kurs: messenjerdagi liddan imzolangan shartnomagacha', 'Biznes-trener Vitaliy Dubovikning (activesales.by) oshxona mebeli dizaynerlari va sotuvchilari uchun katta videokursi. 33 dars va olti soatga yaqin amaliyot: oshxona bozori qanday tuzilgan va unda kim ishtirok etadi, lidlarning qaysi manbalari ishlaydi, salonda nima qilish mumkin va nima mumkin emas, messenjerlarda yozishmani va tayyor skript bo''yicha qo''ng''iroqlarni qanday olib borish kerak, dizayner chek-varag''i va shartnoma tuzish uchun 7 maslahat, xaridor psixologiyasi turlari bo''yicha, 13 ta tipik xato va 10 ta oltin qoida, aloqa o''rnatishning 10 usuli, ehtiyojlar bilan ishlash va taklifni moslashtirish, e''tirozlarni bartaraf etish, nizolarni hal qilish, bitimni yakunlash va sotuvdan keyingi xizmat.', NOW()
FROM "Course" WHERE "slug" = 'sales-kitchens'
ON CONFLICT ("courseId", "locale") DO NOTHING;
INSERT INTO "CourseTranslation" ("id", "courseId", "locale", "title", "subtitle", "description", "updatedAt")
SELECT 'ctr_uz_sales-pharma', "id", 'uz', 'Tibbiyot vakillari uchun faol sotuv', 'Farmatsevtika biznesida shifokorlar va dorixonalar bilan ishlash texnikalari', 'Tibbiyot vakillari, mintaqaviy menejerlar va farmatsevtika kompaniyalari xodimlari uchun videokurs. Ehtiyojni aniqlash, raqobatchilar bilan ishlash, ishontirish va bitimlarni yopish bo''yicha 15 ta amaliy dars. SPIN metodikasi, nizoli vaziyatlar tahlili, tibbiyot vakilining 3 ta oltin qoidasi. Barcha darslar sotuv bo''yicha amaldagi biznes-trener tomonidan yozilgan.', NOW()
FROM "Course" WHERE "slug" = 'sales-pharma'
ON CONFLICT ("courseId", "locale") DO NOTHING;
INSERT INTO "CourseTranslation" ("id", "courseId", "locale", "title", "subtitle", "description", "updatedAt")
SELECT 'ctr_uz_sales-realty', "id", 'uz', 'Ko''chmas mulk sotish texnikalari', 'Rieltorning oltita xatosi va mijozni bitimga olib boradigan taktika', 'Biznes-trener Vitaliy Dubovikning (activesales.by) rieltorlar, agentlar va ko''chmas mulk agentliklari rahbarlari uchun amaliy videokursi. Jismoniy shaxslarga sotish haqida 9 dars: kvartira sotish boshqa sotuvlardan nimasi bilan farq qiladi va rieltor xizmatining qiymati nimada, kvartira sotuvchisining boshida aslida nima bo''layotgani (sakkiz qarindosh, qaynona va OAV''dan iborat aysberg), mijozning o''zi narxni tushirish haqida gapiradigan uch qadam taktikasi hamda oltita tipik xatoning to''liq tahlili: oddiy dangasalik va javob berish tezligi, kvartirani bozordan past «sotib yuborish» urinishi, oila va eksklyuziv bilan manipulyatsiya, yuzaki aniqlangan ehtiyojlar, e''tirozlar bilan ishlay olmaslik va nizoda obro''ni yo''qotish.', NOW()
FROM "Course" WHERE "slug" = 'sales-realty'
ON CONFLICT ("courseId", "locale") DO NOTHING;
INSERT INTO "CourseTranslation" ("id", "courseId", "locale", "title", "subtitle", "description", "updatedAt")
SELECT 'ctr_uz_sales-shoes', "id", 'uz', 'Poyabzal va kiyim do''konidagi sotuv', 'Savdo zalidagi sotuvning yetti bosqichi: aloqadan ikkinchi juftgacha', 'Biznes-trener Vitaliy Dubovikdan (activesales.by) poyabzal va kiyim salonlari sotuvchi-maslahatchilari uchun amaliy videokurs. Besh dars — zaldagi xaridor bilan ishlashning butun sikli: savdo zalida qanday joylashish va yaqinlashish uchun qulay lahzani ilg''ash, qaysi savollar bilan ehtiyojni aniqlash, foyda tilida taqdimotni qanday qilish va uchta quti to''g''ri chiqarish, «qimmat», «shunchaki ko''ryapman», «notanish brenddan qo''rqaman» va «o''ylab ko''raman» javoblariga qanday javob berish, chekni ikkinchi juft va poyabzal parvarishi bilan qanday kengaytirish, sotuvni yakunlashning sakkiz usuli va xaridorni xaridsiz ketishiga sabab bo''ladigan poyabzal sotuvchisining 13 ta tipik xatosi.', NOW()
FROM "Course" WHERE "slug" = 'sales-shoes'
ON CONFLICT ("courseId", "locale") DO NOTHING;
INSERT INTO "CourseTranslation" ("id", "courseId", "locale", "title", "subtitle", "description", "updatedAt")
SELECT 'ctr_uz_sales-spin', "id", 'uz', 'SPIN-sotuv: ehtiyojni qanday shakllantirish kerak', 'Mijozni sotib olish qaroriga olib keladigan savollarning to''rt turi', 'Biznes-trener Vitaliy Dubovikdan (activesales.by) SPIN usuli bo''yicha amaliy videokurs. Ko''pchilik sotuvchilar ehtiyojni ochiq savollar bilan aniqlay oladi, lekin uni shakllantirishni deyarli hech kim bilmaydi — aynan shu maslahatchini sotuvchidan ajratadi. Yetti dars: savollarning to''rt turi (situatsion, muammoli, chiqaruvchi, yo''naltiruvchi), «fakt → foyda → rozilik» taqdimot sxemasi va oltita soha uchun tayyor savollar to''plami — qurilish supermarketi va DIY, soatlar saloni, B2B''ga uskuna yetkazib berish, bank va lizing, ekspert xizmatlarini sotish va hatto bola bilan o''qish haqidagi suhbat.', NOW()
FROM "Course" WHERE "slug" = 'sales-spin'
ON CONFLICT ("courseId", "locale") DO NOTHING;
INSERT INTO "CourseTranslation" ("id", "courseId", "locale", "title", "subtitle", "description", "updatedAt")
SELECT 'ctr_uz_sales-tourism', "id", 'uz', 'Turizmda sotuv texnikalari', 'Kiruvchi qo''ng''iroqdan takroriy sayohatgacha: algoritm, savollar, turist turlari', 'Biznes-trener Vitaliy Dubovikning (activesales.by) turagentliklar va turoperatorlar menejerlari uchun amaliy videokursi. Haqiqiy trening bo''yicha 13 dars: turistning qarori nimalardan shakllanadi (mahsulot, kompaniya va sotuvchi — sotuvchiga ta''sirning 87 %''igacha to''g''ri keladi), sotuvchining to''rt roli, bitim sikli turist ko''zi bilan, tipik xatolar va xavf zonalari, to''qqiz qadamdan iborat kiruvchi qo''ng''iroq algoritmi, savollar voronkasi (ochiq → muqobil → yopiq), turistlarning to''rt turi va har biriga moslashish, «qimmat», «shunchaki o''rganyapman» va «o''ylab ko''raman» javoblariga tayyor javoblar, nizo bilan ishlash, bitimni yopishning besh usuli va sayohatdan keyin turistni qaytarish.', NOW()
FROM "Course" WHERE "slug" = 'sales-tourism'
ON CONFLICT ("courseId", "locale") DO NOTHING;
INSERT INTO "CourseTranslation" ("id", "courseId", "locale", "title", "subtitle", "description", "updatedAt")
SELECT 'ctr_uz_time-management', "id", 'uz', 'Taym-menejment: asosiy tamoyillar', 'Ustuvorliklar, maqsadlar va vaqtni boshqarish vositalari — Vitaliy Dubovik treningi', 'Biznes-trener Vitaliy Dubovikdan (activesales.by) taym-menejment bo''yicha amaliy videokurs. 18 dars — bazaviy tamoyillardan tayyor vositalargacha: Eyzenxauer matritsasi bo''yicha ustuvorliklarni qanday belgilash, kunni 60/40 qoidasi bilan rejalashtirish, «baqadan» boshlash, yirik vazifalarni «fil» va «uch mix» texnikasi bilan bo''lish, maqsadni to''g''ri qo''yish, kundalik va Google Kalendarni yuritish, xronometraj orqali «vaqt yeguvchilarni» topish hamda ofisda ham, masofadan ham samarali ishni tashkil qilish. Material B2B''dagi jonli treninglarda suratga olingan, lekin barcha modellar universal.', NOW()
FROM "Course" WHERE "slug" = 'time-management'
ON CONFLICT ("courseId", "locale") DO NOTHING;
